// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_v0w3Pctcu",
    "aws_user_pools_web_client_id": "1jf2npg34nsnj9jfvh58m5o2ja",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://shppa7kkqfcankmq3yv65dtjrq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k34pf57ye5bfvgvjqoumzwnmsu",
    "aws_content_delivery_bucket": "twistter7-20190929123904-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://twistter7-20190929123904-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
